import React, { useState, useMemo } from 'react'
import { MemberRecord } from '../types'
import {
  Search,
  Filter,
  Download,
  Calendar,
  Users,
  Award,
  BarChart3,
  Plus,
  RefreshCw,
  FileSpreadsheet,
  FileCode,
  FileText
} from 'lucide-react'

interface DataViewerProps {
  members: MemberRecord[]
  onAddMember: (member: MemberRecord) => void
  onResetData: () => void
}

export const DataViewer: React.FC<DataViewerProps> = ({
  members,
  onAddMember,
  onResetData
}) => {
  const [dateFilter, setDateFilter] = useState('2026-09-06')
  const [teamFilter, setTeamFilter] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [showAddModal, setShowAddModal] = useState(false)

  // Form state
  const [newName, setNewName] = useState('')
  const [newDate, setNewDate] = useState('2026-09-06')
  const [newTeam, setNewTeam] = useState<'Alpha' | 'Beta' | 'Gamma'>('Alpha')
  const [newRole, setNewRole] = useState('')
  const [newScore, setNewScore] = useState(90)

  // Filtered dataset
  const filteredMembers = useMemo(() => {
    return members.filter(item => {
      const matchDate = !dateFilter || item.date.includes(dateFilter.trim())
      const matchTeam = !teamFilter || item.team === teamFilter
      const matchSearch =
        !searchQuery ||
        item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.role.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.team.toLowerCase().includes(searchQuery.toLowerCase()) ||
        String(item.score).includes(searchQuery)
      return matchDate && matchTeam && matchSearch
    })
  }, [members, dateFilter, teamFilter, searchQuery])

  // Analytics Metrics
  const metrics = useMemo(() => {
    const total = filteredMembers.length
    if (total === 0) {
      return { total: 0, avgScore: 0, topTeam: '—', highestScore: 0 }
    }
    const sum = filteredMembers.reduce((acc, m) => acc + m.score, 0)
    const avgScore = Number((sum / total).toFixed(1))
    const highestScore = Math.max(...filteredMembers.map(m => m.score))

    const teamCounts: Record<string, number> = {}
    filteredMembers.forEach(m => {
      teamCounts[m.team] = (teamCounts[m.team] || 0) + 1
    })

    let topTeam = '—'
    let maxCount = 0
    for (const [team, count] of Object.entries(teamCounts)) {
      if (count > maxCount) {
        maxCount = count
        topTeam = team
      }
    }

    return { total, avgScore, topTeam, highestScore }
  }, [filteredMembers])

  // Export handlers
  const handleExportCSV = () => {
    const headers = ['name', 'date', 'team', 'role', 'score']
    const csvRows = [
      headers.join(','),
      ...filteredMembers.map(m => [m.name, m.date, m.team, m.role, m.score].join(','))
    ]
    const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `vexorion_export_${dateFilter || 'all'}.csv`
    link.click()
    URL.revokeObjectURL(url)
  }

  const handleExportJSON = () => {
    const jsonStr = JSON.stringify(filteredMembers, null, 2)
    const blob = new Blob([jsonStr], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `vexorion_export_${dateFilter || 'all'}.json`
    link.click()
    URL.revokeObjectURL(url)
  }

  const handleExportHTML = () => {
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>NewVexorion Export - ${dateFilter || 'All'}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; background: #0f172a; color: #f8fafc; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; background: #1e293b; border-radius: 8px; overflow: hidden; }
    th, td { padding: 12px 16px; text-align: left; border-bottom: 1px solid #334155; }
    th { background: #0284c7; color: white; text-transform: uppercase; font-size: 12px; }
  </style>
</head>
<body>
  <h1>NewVexorion Exported Records</h1>
  <p>Generated by NewVexorion Library • Filter: ${dateFilter || 'All'} • Count: ${filteredMembers.length}</p>
  <table>
    <thead>
      <tr>
        <th>Name</th><th>Date</th><th>Team</th><th>Role</th><th>Score</th>
      </tr>
    </thead>
    <tbody>
      ${filteredMembers
        .map(
          m =>
            `<tr><td><strong>${m.name}</strong></td><td>${m.date}</td><td>${m.team}</td><td>${m.role}</td><td>${m.score}</td></tr>`
        )
        .join('')}
    </tbody>
  </table>
</body>
</html>`
    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `vexorion_table_${dateFilter || 'all'}.html`
    link.click()
    URL.revokeObjectURL(url)
  }

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!newName.trim() || !newRole.trim()) return
    onAddMember({
      name: newName.trim(),
      date: newDate.trim(),
      team: newTeam,
      role: newRole.trim(),
      score: Number(newScore) || 80
    })
    setNewName('')
    setNewRole('')
    setShowAddModal(false)
  }

  return (
    <div className="space-y-6">
      {/* Metric Cards Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-slate-800/70 border border-slate-700/60 rounded-xl p-4 flex items-center gap-3 shadow-xs">
          <div className="w-10 h-10 rounded-lg bg-blue-500/10 text-blue-400 flex items-center justify-center">
            <Users className="w-5 h-5" />
          </div>
          <div>
            <div className="text-2xl font-bold text-white tracking-tight">{metrics.total}</div>
            <div className="text-xs text-slate-400 font-medium">Matching Members</div>
          </div>
        </div>

        <div className="bg-slate-800/70 border border-slate-700/60 rounded-xl p-4 flex items-center gap-3 shadow-xs">
          <div className="w-10 h-10 rounded-lg bg-emerald-500/10 text-emerald-400 flex items-center justify-center">
            <BarChart3 className="w-5 h-5" />
          </div>
          <div>
            <div className="text-2xl font-bold text-white tracking-tight">{metrics.avgScore}</div>
            <div className="text-xs text-slate-400 font-medium">Average Score</div>
          </div>
        </div>

        <div className="bg-slate-800/70 border border-slate-700/60 rounded-xl p-4 flex items-center gap-3 shadow-xs">
          <div className="w-10 h-10 rounded-lg bg-purple-500/10 text-purple-400 flex items-center justify-center">
            <Award className="w-5 h-5" />
          </div>
          <div>
            <div className="text-2xl font-bold text-white tracking-tight">{metrics.topTeam}</div>
            <div className="text-xs text-slate-400 font-medium">Dominant Team</div>
          </div>
        </div>

        <div className="bg-slate-800/70 border border-slate-700/60 rounded-xl p-4 flex items-center gap-3 shadow-xs">
          <div className="w-10 h-10 rounded-lg bg-amber-500/10 text-amber-400 flex items-center justify-center">
            <Calendar className="w-5 h-5" />
          </div>
          <div>
            <div className="text-2xl font-bold text-white tracking-tight">{dateFilter || 'All'}</div>
            <div className="text-xs text-slate-400 font-medium">Active Filter Date</div>
          </div>
        </div>
      </div>

      {/* Control Panel */}
      <div className="bg-slate-800/60 border border-slate-700/60 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex flex-wrap items-center gap-3 flex-1">
          {/* Date Filter */}
          <div className="flex items-center gap-2 bg-slate-900/80 border border-slate-700 px-3 py-1.5 rounded-lg text-xs">
            <Calendar className="w-3.5 h-3.5 text-blue-400" />
            <input
              type="text"
              value={dateFilter}
              onChange={e => setDateFilter(e.target.value)}
              placeholder="e.g. 2026-09-06"
              className="bg-transparent border-none text-slate-200 focus:outline-none w-28 text-xs font-mono"
            />
            {dateFilter && (
              <button
                onClick={() => setDateFilter('')}
                className="text-slate-500 hover:text-slate-300 ml-1 text-xs"
                title="Clear date filter"
              >
                ×
              </button>
            )}
          </div>

          {/* Team Filter */}
          <div className="flex items-center gap-2 bg-slate-900/80 border border-slate-700 px-3 py-1.5 rounded-lg text-xs">
            <Filter className="w-3.5 h-3.5 text-purple-400" />
            <select
              value={teamFilter}
              onChange={e => setTeamFilter(e.target.value)}
              className="bg-transparent border-none text-slate-200 focus:outline-none text-xs cursor-pointer"
            >
              <option value="" className="bg-slate-900">All Teams</option>
              <option value="Alpha" className="bg-slate-900">Team Alpha</option>
              <option value="Beta" className="bg-slate-900">Team Beta</option>
              <option value="Gamma" className="bg-slate-900">Team Gamma</option>
            </select>
          </div>

          {/* Keyword Search */}
          <div className="flex items-center gap-2 bg-slate-900/80 border border-slate-700 px-3 py-1.5 rounded-lg text-xs flex-1 min-w-[160px]">
            <Search className="w-3.5 h-3.5 text-slate-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="Search member, role, team..."
              className="bg-transparent border-none text-slate-200 focus:outline-none w-full text-xs"
            />
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowAddModal(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-medium transition cursor-pointer"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Add Member</span>
          </button>

          <button
            onClick={handleExportCSV}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-200 text-xs transition cursor-pointer"
            title="Export CSV"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-400" />
            <span className="hidden sm:inline">CSV</span>
          </button>

          <button
            onClick={handleExportJSON}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-200 text-xs transition cursor-pointer"
            title="Export JSON"
          >
            <FileCode className="w-3.5 h-3.5 text-amber-400" />
            <span className="hidden sm:inline">JSON</span>
          </button>

          <button
            onClick={handleExportHTML}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-200 text-xs transition cursor-pointer"
            title="Export HTML"
          >
            <FileText className="w-3.5 h-3.5 text-blue-400" />
            <span className="hidden sm:inline">HTML</span>
          </button>

          <button
            onClick={onResetData}
            className="p-1.5 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-300 transition cursor-pointer"
            title="Reset dataset to default"
          >
            <RefreshCw className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Data Table */}
      <div className="bg-slate-800/70 border border-slate-700/60 rounded-xl overflow-hidden shadow-xs">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="bg-slate-900/90 text-slate-400 text-xs uppercase tracking-wider border-b border-slate-700/60">
              <tr>
                <th className="py-3 px-4 font-semibold">Member</th>
                <th className="py-3 px-4 font-semibold">Date</th>
                <th className="py-3 px-4 font-semibold">Team</th>
                <th className="py-3 px-4 font-semibold">Role</th>
                <th className="py-3 px-4 font-semibold text-right">Performance Score</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-700/40">
              {filteredMembers.length > 0 ? (
                filteredMembers.map((member, idx) => (
                  <tr key={idx} className="hover:bg-slate-700/30 transition">
                    <td className="py-3 px-4 text-white font-medium flex items-center gap-2">
                      <div className="w-7 h-7 rounded-full bg-slate-700 text-slate-300 flex items-center justify-center text-xs font-bold uppercase">
                        {member.name.charAt(0)}
                      </div>
                      <span>{member.name}</span>
                    </td>
                    <td className="py-3 px-4 font-mono text-xs text-slate-300">
                      {member.date}
                    </td>
                    <td className="py-3 px-4">
                      <span
                        className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-semibold ${
                          member.team === 'Alpha'
                            ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                            : member.team === 'Beta'
                            ? 'bg-purple-500/20 text-purple-400 border border-purple-500/30'
                            : 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                        }`}
                      >
                        {member.team}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-slate-300">{member.role}</td>
                    <td className="py-3 px-4 text-right">
                      <div className="inline-flex items-center gap-2">
                        <span className="font-semibold text-slate-100">{member.score}</span>
                        <div className="w-16 h-1.5 bg-slate-700 rounded-full overflow-hidden hidden sm:block">
                          <div
                            className={`h-full rounded-full ${
                              member.score >= 90
                                ? 'bg-emerald-500'
                                : member.score >= 80
                                ? 'bg-blue-500'
                                : 'bg-amber-500'
                            }`}
                            style={{ width: `${Math.min(member.score, 100)}%` }}
                          />
                        </div>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} className="py-8 text-center text-slate-400">
                    No members found matching the specified date or criteria.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        <div className="p-3 bg-slate-900/60 border-t border-slate-700/50 flex items-center justify-between text-xs text-slate-400">
          <span>Showing {filteredMembers.length} of {members.length} records</span>
          <span>Source: NewVexorion Core Ingestion Layer</span>
        </div>
      </div>

      {/* Add Member Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-slate-800 border border-slate-700 rounded-xl p-6 w-full max-w-md shadow-xl">
            <h3 className="text-lg font-bold text-white mb-4">Add Member Record</h3>
            <form onSubmit={handleFormSubmit} className="space-y-4">
              <div>
                <label className="block text-xs text-slate-300 mb-1">Full Name</label>
                <input
                  type="text"
                  required
                  value={newName}
                  onChange={e => setNewName(e.target.value)}
                  placeholder="e.g. Grace Hopper"
                  className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-blue-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs text-slate-300 mb-1">Date (YYYY-MM-DD)</label>
                  <input
                    type="text"
                    required
                    value={newDate}
                    onChange={e => setNewDate(e.target.value)}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-blue-500 font-mono"
                  />
                </div>

                <div>
                  <label className="block text-xs text-slate-300 mb-1">Team</label>
                  <select
                    value={newTeam}
                    onChange={e => setNewTeam(e.target.value as any)}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-blue-500"
                  >
                    <option value="Alpha">Alpha</option>
                    <option value="Beta">Beta</option>
                    <option value="Gamma">Gamma</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs text-slate-300 mb-1">Role</label>
                  <input
                    type="text"
                    required
                    value={newRole}
                    onChange={e => setNewRole(e.target.value)}
                    placeholder="e.g. Lead Architect"
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-xs text-slate-300 mb-1">Score (0-100)</label>
                  <input
                    type="number"
                    min="0"
                    max="100"
                    value={newScore}
                    onChange={e => setNewScore(Number(e.target.value))}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-blue-500"
                  />
                </div>
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-4 py-2 rounded-lg bg-slate-700 hover:bg-slate-600 text-slate-200 text-xs font-medium cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-medium cursor-pointer"
                >
                  Save Record
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}
