/**
 * Client-side script for standard web viewer.
 * Directly imports and demonstrates NewVexorion library classes!
 */
import { CSVParser, DataSearcher } from '../src/browser.js'

// Sample data in raw CSV format (as generated by Vexorion pipeline)
const rawCSV = `name,date,team,role,score
Alice Johnson,2026-09-06,Alpha,Engineer,95
Bob Smith,2026-09-06,Beta,Analyst,88
Charlie Brown,2026-09-05,Alpha,Designer,92
Diana Prince,2026-09-06,Gamma,Team Lead,98
Evan Wright,2026-09-06,Alpha,Developer,85
Fiona Gallagher,2026-09-04,Beta,Product Manager,90
George Clark,2026-09-06,Beta,Tester,78
Hannah Abbott,2026-09-06,Alpha,DevOps,94
Ian Malcolm,2026-09-06,Gamma,Scientist,96
Julia Roberts,2026-09-03,Beta,Coordinator,82`

// Parse using NewVexorion CSVParser
const parser = new CSVParser({ delimiter: ',', hasHeader: true })
const parseResult = parser.parse(rawCSV)

// Initialize NewVexorion DataSearcher with parsed objects
const searcher = new DataSearcher(parseResult.data, ['name', 'date', 'team', 'role', 'score'])

function renderTable(items) {
  const tbody = document.getElementById('dataBody')
  tbody.innerHTML = ''

  items.forEach(item => {
    const tr = document.createElement('tr')
    const fields = ['name', 'date', 'team', 'role', 'score']
    fields.forEach(f => {
      const td = document.createElement('td')
      td.textContent = item[f] !== undefined ? item[f] : ''
      tr.appendChild(td)
    })
    tbody.appendChild(tr)
  })

  document.getElementById('counterText').textContent = `${items.length} records found (via NewVexorion DataSearcher)`
}

function filterData() {
  const filterVal = document.getElementById('filterInput').value.trim()
  
  // Use NewVexorion DataSearcher methods directly
  let filtered
  if (filterVal) {
    filtered = searcher.filterByDate(filterVal)
    if (filtered.length === 0) {
      filtered = searcher.search(filterVal)
    }
  } else {
    filtered = parseResult.data
  }

  renderTable(filtered)
  document.getElementById('statusText').textContent = `Filtered with "${filterVal || 'all'}"`
}

document.getElementById('loadBtn').addEventListener('click', filterData)
document.getElementById('filterInput').addEventListener('keyup', (e) => {
  if (e.key === 'Enter') filterData()
})

// Initial load
document.getElementById('filterInput').value = '2026-09-06'
filterData()
